name: cirrodrive
services:
  frontend:
    image: cirrodrive-frontend:latest
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: frontend
    ports:
      - "${CLIENT_PORT}:80"
    restart: always
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  backend:
    image: cirrodrive-backend:latest
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
    volumes:
      - ${CIRRODRIVE_HOME}/cirrodrive-app-data:/cirrodrive/apps/backend/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  cirrodrive-app-data:
    external: false
