version: "3.8"

services:
  api:
    extends:
      file: compose.yml
      service: api
    environment:
      - DATABASE_URL=mysql://dev_user:dev_password@db:3306/dev_db
    volumes:
      - ./local_api_data:/app/data
    ports:
      - 8001:8000

  db:
    extends:
      file: compose.yml
      service: db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=dev_db
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=dev_password

volumes:
  local_api_data:
  local_db_data:
