name: cirrodrive
services:
  frontend:
    image: zetabs/cirrodrive:frontend
    container_name: frontend
    ports:
      - "${CLIENT_PORT}:80"
    restart: always
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  backend:
    image: zetabs/cirrodrive:backend
    container_name: backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
    volumes:
      - ${CIRRODRIVE_HOME}/cirrodrive-app-data:/cirrodrive/apps/backend/data
      - ./env/backend.env:/cirrodrive/apps/backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  cirrodrive-app-data:
    external: false
