name: cirrodrive
services:
  frontend:
    image: cirrodrive-frontend:latest
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: frontend
    ports:
      - "${VITE_CLIENT_PORT}:80"
    restart: always
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  frontend-dev:
    image: cirrodrive-frontend:latest
    container_name: frontend-dev
    ports:
      - "${VITE_CLIENT_PORT}:80"
    restart: always
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  backend:
    image: cirrodrive-backend:latest
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: backend
    ports:
      - "${VITE_SERVER_PORT}:${VITE_SERVER_PORT}"
    restart: always
    depends_on:
      database:
        condition: service_healthy
        restart: true
    volumes:
      - ${CIRRODRIVE_HOME}/cirrodrive-app-data:/cirrodrive/apps/backend/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  backend-dev:
    image: cirrodrive-backend:latest
    container_name: backend-dev
    ports:
      - "${VITE_SERVER_PORT}:${VITE_SERVER_PORT}"
    restart: always
    depends_on:
      database:
        condition: service_healthy
        restart: true
    volumes:
      - cirrodrive-app-data:/cirrodrive/apps/backend/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  database:
    extends:
      file: ./apps/database/compose.yaml
      service: database

volumes:
  cirrodrive-app-data:
    external: false
