name: cirrodrive
services:
  frontend:
    image: zetabs/cirrodrive:frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: cirrodrive-frontend
    ports:
      - "${APP_CLIENT_PORT}:${APP_CLIENT_PORT}"
    restart: always
    environment:
      - TZ=Asia/Seoul
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_CLIENT_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  backend:
    image: zetabs/cirrodrive:backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: cirrodrive-backend
    ports:
      - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    restart: always
    environment:
      - NODE_ENV=production
      - APP_SERVER_PORT=${APP_SERVER_PORT}
      - APP_CLIENT_PORT=${APP_CLIENT_PORT}
      - APP_PUBLIC_HOST=${APP_PUBLIC_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_DEFAULT_ADMIN_USERNAME=${AUTH_DEFAULT_ADMIN_USERNAME}
      - AUTH_DEFAULT_ADMIN_PASSWORD=${AUTH_DEFAULT_ADMIN_PASSWORD}
      - AWS_REGION=${AWS_REGION}
      - AWS_SES_SOURCE_EMAIL=${AWS_SES_SOURCE_EMAIL}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - PAYMENT_TOSS_SECRET_KEY=${PAYMENT_TOSS_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_SERVER_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  cirrodrive-app-data:
    external: false
