packages:
  - packages/*
  - apps/*
  - tooling/*

catalog:
  "@trpc/client": next
  "@trpc/react-query": next
  "@trpc/server": next
  "@tanstack/react-query": ^5.67.1
  "@tanstack/react-query-devtools": ^5.67.1
  eslint: ^9.12.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.14
  typescript: ^5.7.2
  vite: ^5.4.10
  vitest: ^2.1.4
  "@vitest/coverage-v8": ^2.1.4
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
