packages:
  - packages/*
  - apps/*
  - tooling/*

catalog:
  "@trpc/client": ^11.1.2
  "@trpc/react-query": ^11.1.2
  "@trpc/server": ^11.1.2
  "@trpc/tanstack-react-query": ^11.1.2
  "@tanstack/react-query": ^5.67.1
  "@tanstack/react-query-devtools": ^5.67.1
  "@dotenvx/dotenvx": ^1.44.0
  eslint: ^9.27.0
  prettier: ^3.5.3
  prettier-plugin-jsdoc: ^1.3.2
  prettier-plugin-sort-json: ^4.1.1
  prettier-plugin-packagejson: ^2.5.14
  typescript: ^5.7.2
  vite: ^6.3.5
  vitest: ^3.1.4
  "@vitest/coverage-v8": ^3.1.4
  zod: ^3.25.28
  tsx: ^4.19.4

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
