packages:
  - packages/*
  - apps/*
  - tooling/*

catalog:
  "@trpc/client": ^11.0.0-rc.593
  "@trpc/react-query": ^11.0.0-rc.593
  "@trpc/server": ^11.0.0-rc.593
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  vite: ^5.4.10
  vitest: ^2.1.4
  "@vitest/coverage-v8": ^2.1.4
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
