name: cirrodrive
services:
  frontend:
    build:
      context: ../../
      dockerfile: ./apps/frontend/Dockerfile.prod
    container_name: frontend
    ports:
      - 80:80
    restart: always
    environment:
      - TZ=Asia/Seoul
      - VITE_TRPC_SERVER_URL="http://ec2-3-38-95-198.ap-northeast-2.compute.amazonaws.com"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
