name: cirrodrive-dev
services:
  frontend:
    build:
      context: ../../
      dockerfile: ./apps/frontend/Dockerfile.dev
    container_name: frontend-dev
    ports:
      - 5173:5173
    restart: always
