name: cirrodrive-dev
services:
  frontend-dev:
    build:
      context: ../../
      dockerfile: ./apps/frontend/Dockerfile.dev
    container_name: frontend-dev
    ports:
      - 5173:5173
    restart: always
    environment:
      - TZ=Asia/Seoul
      - VITE_TRPC_SERVER_URL="http://ec2-3-38-95-198.ap-northeast-2.compute.amazonaws.com"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
