name: cirrodrive
services:
  frontend:
    build:
      context: ../../
      dockerfile: ./apps/frontend/Dockerfile.prod
    container_name: frontend
    ports:
      - 80:80
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
