# 1단계: Turbo를 사용해 모노레포를 트림하는 단계
FROM node:20-alpine AS pruner

# 작업 디렉토리를 /repo로 설정
WORKDIR /repo

# 터보 레포 설치
RUN npm install -g turbo

# 모노레포 전체 소스 코드를 컨테이너로 복사
COPY . .

# Turbo prune을 사용해 불필요한 파일을 트림
RUN turbo prune frontend --docker

# 2단계: Vite 개발 서버 실행 단계
FROM node:20-alpine AS dev

# 작업 디렉토리를 /repo로 설정
WORKDIR /repo

# pruner 단계에서 만들어진 의존성 관련 json 파일 복사
COPY --from=pruner /repo/out/json/ .

# 의존성 설치
RUN npm ci

# pruner 단계에서 트림된 전체 소스 파일 복사
COPY --from=pruner /repo/out/full/ .

# 작업 디렉토리를 frontend 애플리케이션으로 변경
WORKDIR /repo/apps/frontend

# Vite 개발 서버의 5173 포트 노출
EXPOSE 5173

# Vite 개발 서버를 실행
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
