name: cirrodrive-dev
services:
  backend-dev:
    build:
      context: ../../
      dockerfile: ./apps/backend/Dockerfile.dev
    container_name: backend-dev
    ports:
      - 3000:3000
    restart: always
    volumes:
      - app-data:/cirrodrive/apps/backend/data
    depends_on:
      database-dev:
        condition: service_healthy
        restart: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  database-dev:
    image: mariadb:11.4.3-noble
    container_name: database-dev
    ports:
      - 3307:3307
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --port=3307
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=apiuser
      - MARIADB_PASSWORD=apipassword
      - MARIADB_DATABASE=apidatabase
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  app-data:
    external: false
  database-data:
    external: false
