name: cirrodrive
services:
  backend:
    build:
      context: ../../
      dockerfile: ./apps/backend/Dockerfile.prod
    container_name: backend
    ports:
      - 8000:8000
    restart: always
    volumes:
      - app-data:/repo/apps/backend/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      database:
        condition: service_healthy
        restart: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  database:
    image: mariadb:11.4.3-noble
    container_name: database
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  app-data:
    external: true
  database-data:
    external: true
