# 기본 이미지 설정
FROM node:20.16 AS base
# 환경 변수 설정
ENV TURBO_TELEMETRY_DISABLED=1
# pnpm 설정
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
# turborepo 설치
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install -g turbo
# 작업 디렉터리 설정
WORKDIR /cirrodrive
# turborepo 설정 파일 복사
COPY turbo.json .

# 모노레포 정리
FROM base AS prune
# 모노레포 복사
COPY . .
# 불필요한 파일 정리
RUN pnpx turbo prune @cirrodrive/backend --docker
# 결과 압축
RUN tar -czf json.tar.gz -C ./out/json . && \
  tar -czf full.tar.gz -C ./out/full .

# 의존성 설치
FROM base AS deps
# 의존성 파일 복사
COPY --from=prune /cirrodrive/json.tar.gz .
RUN tar -xzf json.tar.gz -C . && rm json.tar.gz
# 의존성 설치
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# 실행 이미지 설정
FROM deps AS runner
# 환경 변수 설정
ENV VITE_PORT=3000
ENV DATABASE_URL=mysql://apiuser:apipassword@database-dev:3307/apidatabase
# 전체 파일 복사
COPY --from=prune /cirrodrive/full.tar.gz .
RUN tar -xzf full.tar.gz -C . && rm full.tar.gz
# prisma 클라이언트 생성
RUN pnpm -F @cirrodrive/backend run prisma:generate
# 3000번 포트 노출
EXPOSE 3000
# 실행 명령어
ENTRYPOINT [ "pnpm", "-F", "@cirrodrive/backend", "run", "dev" ]