name: Setup Node, pnpm, turbo cache, and dependencies
description: |
  This action sets up Node.js, pnpm, and restores turbo cache and eslint cache.
  It is used in the CI workflow to ensure a consistent environment for running tests and linting.
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.19.1
        cache: "pnpm"

    - name: Restore turbo cache
      uses: actions/cache@v4
      with:
        path: "**/.turbo/**"
        key: turbo-${{ runner.os }}-${{ hashFiles('**/turbo.json', '**/package.json', '**/pnpm-lock.yaml') }}
        restore-keys: |
          turbo-${{ runner.os }}-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline
      shell: bash
