name: Setup Environment
description: Common environment setup for all jobs
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.19.1
        cache: "pnpm"

    - name: Restore turbo cache
      uses: actions/cache@v4
      with:
        path: .turbo
        key: turbo-${{ runner.os }}-${{ hashFiles('**/turbo.json', '**/package.json', '**/pnpm-lock.yaml') }}
        restore-keys: |
          turbo-${{ runner.os }}-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline
      shell: bash
