name: CI Pipeline

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  lint:
    name: CI (Lint)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node, pnpm, turbo cache, and dependencies
        uses: ./.github/actions/setup-node-pnpm

      - name: Restore eslint cache
        uses: actions/cache@v4
        with:
          path: "**/.cache/.eslintcache"
          key: eslint-${{ runner.os }}-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml', '**/eslint.config.js') }}
          restore-keys: |
            eslint-${{ runner.os }}-

      - name: Run lint
        run: pnpm lint

  typecheck:
    name: CI (TypeCheck)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node, pnpm, turbo cache, and dependencies
        uses: ./.github/actions/setup-node-pnpm

      - name: Restore typecheck cache
        uses: actions/cache@v4
        with:
          path: "**/.cache/tsbuildinfo.json"
          key: typecheck-${{ runner.os }}-${{ hashFiles('**/tsconfig.json', '**/package.json', '**/pnpm-lock.yaml') }}
          restore-keys: |
            typecheck-${{ runner.os }}-

      - name: Run typecheck
        run: pnpm typecheck

  test:
    name: CI (Test)
    runs-on: ubuntu-22.04
    env:
      # 백엔드
      APP_SERVER_PORT: 4000
      APP_CLIENT_PORT: 5173
      APP_PUBLIC_HOST: localhost
      DATABASE_URL: mysql://mariadb:mariadb@localhost:3306/mariadb-test
      AUTH_JWT_SECRET: test-secret
      AUTH_DEFAULT_ADMIN_USERNAME: admin
      AUTH_DEFAULT_ADMIN_PASSWORD: secure-password
      AWS_REGION: ap-northeast-2
      AWS_SES_SOURCE_EMAIL: your-verified-email@example.com
      AWS_S3_BUCKET: test-bucket
      AWS_S3_ACCESS_KEY: minioadmin
      AWS_S3_SECRET_KEY: minioadmin
      AWS_S3_ENDPOINT: http://localhost:9000
      PAYMENT_TOSS_SECRET_KEY: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R
      # 프론트엔드
      VITE_API_HOST: localhost
      VITE_API_PORT: 4000
      VITE_TOSS_CLIENT_KEY: test_ck_D5GePWvyJnrK0W0k6q8gLzN97Eoq
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node, pnpm, turbo cache, and dependencies
        uses: ./.github/actions/setup-node-pnpm

      - name: Restore test cache
        uses: actions/cache@v4
        with:
          path: "**/.cache/vitest-report.json"
          key: test-${{ runner.os }}-${{ hashFiles('**/vitest.config.ts', '**/package.json', '**/pnpm-lock.yaml') }}
          restore-keys: |
            test-${{ runner.os }}-

      - name: Clear dotenv files
        run: find . -name ".env*" -type f -print -delete

      - name: Start compose services
        run: docker compose -f docker-compose-ci.yml up -d

      - name: Wait for MariaDB healthcheck
        run: |
          for i in {1..30}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' $(docker compose -f docker-compose-ci.yml ps -q db))
            echo "MariaDB health status: $status"
            if [ "$status" = "healthy" ]; then
              echo "MariaDB is healthy!"
              exit 0
            fi
            sleep 2
          done
          echo "MariaDB did not become healthy in time" && exit 1

      - name: Run tests
        run: pnpm test:ci

  notify-success:
    name: Notify Success
    runs-on: ubuntu-22.04
    needs: [lint, typecheck, test]
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get commit info
        id: commit-info
        run: |
          echo "commit_sha=$(git log -1 --pretty=%h)" >> $GITHUB_OUTPUT

      - name: Get test details
        id: test-details
        run: |
          # 현재 시간 (KST)
          NOW=$(TZ=Asia/Seoul date +"%Y-%m-%d %H:%M:%S %Z")
          echo "test_time=$NOW" >> $GITHUB_OUTPUT
          echo "workflow_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Notify Discord Success
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: success
          title: "✅ CI 테스트 성공"
          description: |
            **환경:** CI
            **테스트 시간:** ${{ steps.test-details.outputs.test_time }}
            **브랜치:** ${{ github.ref_name }}
            **커밋:** [${{ steps.commit-info.outputs.commit_sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          color: 3066993
          url: ${{ steps.test-details.outputs.workflow_url }}
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png

  notify-failure:
    name: Notify Failure
    runs-on: ubuntu-22.04
    needs: [lint, typecheck, test]
    if: always() && failure()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get commit info
        id: commit-info
        run: |
          echo "commit_sha=$(git log -1 --pretty=%h)" >> $GITHUB_OUTPUT

      - name: Get test details
        id: test-details
        run: |
          # 현재 시간 (KST)
          NOW=$(TZ=Asia/Seoul date +"%Y-%m-%d %H:%M:%S %Z")
          echo "test_time=$NOW" >> $GITHUB_OUTPUT
          echo "workflow_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Get failure jobs
        id: failure-jobs
        run: |
          FAILURES=""
          if [[ "${{ needs.lint.result }}" == "failure" ]]; then
            FAILURES="${FAILURES}* Lint\n"
          fi
          if [[ "${{ needs.typecheck.result }}" == "failure" ]]; then
            FAILURES="${FAILURES}* TypeCheck\n"
          fi
          if [[ "${{ needs.test.result }}" == "failure" ]]; then
            FAILURES="${FAILURES}* Tests\n"
          fi
          echo "failures=${FAILURES}" >> $GITHUB_OUTPUT

      - name: Notify Discord Failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: failure
          content: "@here CI 테스트에 실패했습니다! 확인이 필요합니다."
          title: "❌ CI 테스트 실패"
          description: |
            **환경:** CI
            **테스트 시간:** ${{ steps.test-details.outputs.test_time }}
            **브랜치:** ${{ github.ref_name }}
            **커밋:** [${{ steps.commit-info.outputs.commit_sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})

            **실패한 작업:**
            ${{ steps.failure-jobs.outputs.failures }}
          color: 15158332
          url: ${{ steps.test-details.outputs.workflow_url }}
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
