name: CI Pipeline

on:
  # Trigger the workflow on push or pull request events to the main branch,
  # but only when changes are made in specified paths (apps, packages, tooling, etc.)
  push:
    branches: [main, develop]
    paths:
      - "apps/**/src/**"
      - "apps/**/test/**"
      - "packages/**"
      - "tooling/**"
      - "eslint.config.js"
      - "pnpm-workspace.yaml"
      - "turbo.json"
      - "pnpm-lock.yaml"

jobs:
  lint:
    name: CI (Lint)
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/setup
      - run: pnpm lint

  typecheck:
    name: CI (TypeCheck)
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/setup
      - run: pnpm typecheck

  test:
    name: CI (Test)
    runs-on: ubuntu-22.04
    steps:
      - name: Run tests in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pnpm test
      - uses: ./.github/actions/setup
      - run: pnpm test
