name: CI Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - "apps/**/src/**"
      - "apps/**/test/**"
      - "packages/**"
      - "tooling/**"
      - "eslint.config.js"
      - "pnpm-workspace.yaml"
      - "turbo.json"
      - "pnpm-lock.yaml"

jobs:
  lint:
    name: CI (Lint)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run lint
        run: pnpm lint

  typecheck:
    name: CI (TypeCheck)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run typecheck
        run: pnpm typecheck

  test:
    name: CI (Test)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pnpm test
